### ISSUE TITLE
multiCheckbox does not populate values when checkbox values are async

### ISSUE THREAD

**Issue by m0t0r** [formly-js/angular-formly-templates-bootstrap#32]
Working with `multiCheckbox` I found an issue. As demonstrated in this [jsbin](http://jsbin.com/janeha/edit?html,js,output). In the first case, I predefine checkbox values in options array, and then I simulate async population of the values and in the UI we can see checked checkbox. In the second case I simulate async loading of the checkbox values and when I populate values, the checkbox is not checked.

**Comment by ckniffen** [comment]
@m0t0r I think this is a problem.  It is because of the funky things that have to be done to get multicheckboxes to work in angular.  The code is not watching the model value for external changes.

The code in questions is here https://github.com/formly-js/angular-formly-templates-bootstrap/blob/26ec0f567172e4f0d75c61897312497b86118182/src/types/multiCheckbox.js#L36-L42.

**Comment by m0t0r** [comment]
@ckniffen, I see. Any chance to get this fixed ? It is blocking me in the project.

**Comment by kentcdodds** [comment]
@m0t0r, you may have to write your own version. I definitely don't have time to implement this new feature.
