### ISSUE TITLE
apiCheck Failed!

### ISSUE THREAD

**Issue by Dog** [formly-js/angular-formly-templates-bootstrap#42]
I get an injection error when I attempt to use formly bootstrap. The error is simply a broken link. Decoding the url, I get the message:

formlyConfig.setWrapper apiCheck failed! Argument value must be object

**Comment by kentcdodds** [comment]
Please reproduce this issue: http://help.angular-formly.com it's helpful to know what versions you're using as well.

**Comment by Dog** [comment]
Here is a plunker with the same issue I have in my code.

http://plnkr.co/edit/OBcOe7OuQ0RPk1V2hrew

**Comment by kentcdodds** [comment]
There was recently a new feature in angular-formly to the `apiCheck` api for wrappers and types. You cannot use angular-formly 6.19.0 with angular-formly-templates-bootstrap 6.0.0 (which your example is doing) because 6.0.0 is using features that 6.20.0 introduced. I recommend that you upgrade the two of these at the same time anytime you upgrade one of them. (and use exact versions rather than version ranges). Here's your example except using the latest versions of both: http://plnkr.co/edit/NmjoKttNrFHsXPmsm1nH?p=preview

Here's the changelog for 6.20.0: http://changelog.angular-formly.com#6200
