### ISSUE TITLE
angular-formly issue with radio

### ISSUE THREAD

**Issue by gaslg** [formly-js/angular-formly-templates-bootstrap#71]
Hello I'm stuck,
how I can show and hide a field based on values of a radio button using ionic-formly
{
            key: 'radioTest',
            type: 'radio',
            templateOptions: {
              options: [{
                value: 'true',
                text: 'YES',
                  }, {
                value: 'false',
                text: 'NO', 
              }]
            }
  },{
            "key": "email",
            "type": "stacked-input",
            "templateOptions": {
                "type":"email",
                "label": "Email",                       
                "placeholder": "Email"
                       },
              "expressionProperties":{
            "hide":function($viewValue,$modelValue,scope){
            return $scope.formData.radioTest
                                                     }
            }
        }

**Comment by kentcdodds** [comment]
If you look in the console, you'll see a warning because you're putting `hide` in `expressionProperties`. It doesn't work very well when you do that. Instead, use `hideExpression`. Please see [the website](http://angular-formly.com) for all the examples and go through the videos on [learn.angular-formly.com](http://learn.angular-formly.com).

Thanks for your interest in angular-formly. Again (I've told you this numerous times before) the best way to get help is by following the instructions at [help.angular-formly.com](http://help.angular-formly.com). The GitHub issues on this project are reserved for feature requests and bug reports, so I'm going to close this issue. See you on [chat](http://chat.angular-formly.com) and [Stack Overflow](http://question.angular-formly.com/)!
