### ISSUE TITLE
data-placeholder attribute is missing from select type.

### ISSUE THREAD

**Issue by khalonen** [formly-js/angular-formly-templates-bootstrap#95]

**Comment by kentcdodds** [comment]
It gets added dynamically for fields which specify a placeholder. You can see this working in most examples. If you have found a bug, could you please reproduce your issue using [issue.angular-formly.com](http://issue.angular-formly.com/)? It will help us determine what exactly the problem is that you're describing and how it could be fixed. Thanks!

**Comment by khalonen** [comment]
Great work!
http://jsbin.com/luvapihaxo/1/edit?html,js,output

Br, Kai

**Comment by kentcdodds** [comment]
Ah yes, I see the problem. Unfortunately, HTML `<select>` elements [cannot have a placeholder](https://jsbin.com/puvenoq/edit?html,css,js,output).

You'll have to either have a default option that acts as a placeholder or use a different solution for a select box. Like: http://angular-formly.com/#/example/integrations/ui-select-angular-1-4

**Comment by khalonen** [comment]
Hi Kent

There should be data-placeholder attribute. Like this

<select class="form-control input-xlarge select2me" data-placeholder="title">
<option value="Kai Halonen">Kai Halonen</option>
<option value="Tommi Vallinmäki">Tommi Vallinmäki</option>
</select>

Br, Kaitsu

**Comment by kentcdodds** [comment]
As you can see, even `data-placeholder` doesn't create any placeholder text for the select: https://jsbin.com/puvenoq/3/edit?html,css,js,output

**Comment by khalonen** [comment]
Hi Kent

I didn’t’ notice that it is done using jquery or select2 library☺
http://jsfiddle.net/MauriceG/fMwQS/

I will try this http://jsfiddle.net/LXp4h/

Thanks.

Br, Kaitsu
